# https://developer.blender.org/docs/features/extensions/schema/1.0.0/
schema_version = "1.0.0"

maintainer = "Daniel Boxer <uvgami@danielboxer.dev>"
type = "add-on"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2022-2026 Daniel Boxer"]

id = "uvgami"
name = "UVgami"
version = "2.0.0"
blender_version_min = "4.3.0"
tagline = "Automatic UV unwrapping"
website = "https://github.com/DanielBoxer/UVgami"

# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["UV"]

[permissions]
files = "Import/export OBJ"
network = "Download the unwrapping engines from GitHub releases"
