"""Feature seams by strip merging, the hard surface Seams mode.

Modules in pipeline order: mesh, regions, sweeps, cuts, boundaries,
islands, pipeline. uv_transfer and proxy_transfer read an unwrapped copy's
uv map back onto a mesh."""

from .boundaries import boundary_edges, flatten_teeth, reroute_boundaries
from .cancel import Cancelled, check_cancelled
from .cuts import (
    TURN_COST,
    connect_loops,
    crease_relief,
    cut_path,
    disk_cuts,
    path_cost,
    snap_paths,
)
from .islands import (
    crosses,
    island_eulers,
    island_ruined,
    split_islands,
    split_moves,
    uv_topology,
)
from .mesh import (
    LOW_ANGLE,
    build,
    cross,
    diagonal,
    face_edges,
    face_keys,
    find,
    island_groups,
    island_layout,
    islands_overlap,
    norm,
    pair,
    signed_area,
    turn_angle,
    uv_area_fit,
    uv_fit,
    uv_island_groups,
    uv_seams,
    uvs_collapsed,
    vertex_components,
)
from .parallel import seam_edges_parallel
from .pipeline import is_hard_surface, seam_edges
from .preseed import (
    FlattenEngine,
    FlattenError,
    check_manifold,
    preseed_uvs,
)
from .rectify import FLIP_NOISE, flatten_distortion, rectify_targets
from .regions import (
    CREASE_ANGLE,
    FLAT_ANGLE,
    absorb,
    close_rings,
    detect_width,
    merge_flat,
    merge_smooth,
    panel_share,
    partition,
    region_topology,
    unfold_hinges,
)
from .sweeps import component_faces, split_sweeps, surface_genus, sweep_rims
from .symmetry import (
    half_faces,
    interface_edges,
    mirror_seams,
    open_merged,
    stack_mirrored,
)

__all__ = [
    "CREASE_ANGLE",
    "FLAT_ANGLE",
    "FLIP_NOISE",
    "LOW_ANGLE",
    "TURN_COST",
    "FlattenEngine",
    "Cancelled",
    "check_cancelled",
    "FlattenError",
    "absorb",
    "boundary_edges",
    "build",
    "check_manifold",
    "close_rings",
    "connect_loops",
    "crease_relief",
    "cross",
    "crosses",
    "cut_path",
    "detect_width",
    "diagonal",
    "disk_cuts",
    "face_edges",
    "face_keys",
    "find",
    "flatten_teeth",
    "half_faces",
    "interface_edges",
    "is_hard_surface",
    "island_groups",
    "island_layout",
    "island_eulers",
    "island_ruined",
    "islands_overlap",
    "flatten_distortion",
    "merge_flat",
    "merge_smooth",
    "mirror_seams",
    "norm",
    "open_merged",
    "pair",
    "partition",
    "path_cost",
    "preseed_uvs",
    "rectify_targets",
    "region_topology",
    "reroute_boundaries",
    "seam_edges",
    "seam_edges_parallel",
    "signed_area",
    "snap_paths",
    "split_islands",
    "split_moves",
    "stack_mirrored",
    "component_faces",
    "surface_genus",
    "panel_share",
    "split_sweeps",
    "sweep_rims",
    "turn_angle",
    "unfold_hinges",
    "uv_area_fit",
    "uv_fit",
    "uv_island_groups",
    "uv_seams",
    "uv_topology",
    "uvs_collapsed",
    "vertex_components",
]
