"""Feature seams by strip merging, the hard surface Seams mode.

Modules in pipeline order: mesh, regions, sweeps, cuts, boundaries,
islands, pipeline."""

from .boundaries import boundary_edges, flatten_teeth, reroute_boundaries
from .cuts import TURN_COST, crease_relief, cut_path, disk_cuts, path_cost, snap_paths
from .islands import crosses, island_ruined, split_islands, uv_topology
from .mesh import (
    LOW_ANGLE,
    build,
    cross,
    diagonal,
    face_edges,
    face_keys,
    find,
    island_groups,
    island_layout,
    islands_overlap,
    norm,
    pair,
    signed_area,
    turn_angle,
    uv_area_fit,
    uv_fit,
    uv_island_groups,
    vertex_components,
)
from .pipeline import is_hard_surface, seam_edges
from .preseed import (
    FlattenEngine,
    FlattenError,
    check_manifold,
    preseed_uvs,
)
from .regions import (
    CREASE_ANGLE,
    FLAT_ANGLE,
    absorb,
    close_rings,
    detect_width,
    merge_flat,
    merge_smooth,
    partition,
    region_topology,
)
from .sweeps import split_sweeps

__all__ = [
    "CREASE_ANGLE",
    "FLAT_ANGLE",
    "LOW_ANGLE",
    "TURN_COST",
    "FlattenEngine",
    "FlattenError",
    "absorb",
    "boundary_edges",
    "build",
    "check_manifold",
    "close_rings",
    "crease_relief",
    "cross",
    "crosses",
    "cut_path",
    "detect_width",
    "diagonal",
    "disk_cuts",
    "face_edges",
    "face_keys",
    "find",
    "flatten_teeth",
    "is_hard_surface",
    "island_groups",
    "island_layout",
    "island_ruined",
    "islands_overlap",
    "merge_flat",
    "merge_smooth",
    "norm",
    "pair",
    "partition",
    "path_cost",
    "preseed_uvs",
    "region_topology",
    "reroute_boundaries",
    "seam_edges",
    "signed_area",
    "snap_paths",
    "split_islands",
    "split_sweeps",
    "turn_angle",
    "uv_area_fit",
    "uv_fit",
    "uv_island_groups",
    "uv_topology",
    "vertex_components",
]
