if(EXISTS "${CMAKE_ROOT}/Modules/CPack.cmake")
  if(EXISTS "${CMAKE_ROOT}/Modules/InstallRequiredSystemLibraries.cmake")
    set(CMAKE_INSTALL_DEBUG_LIBRARIES 0)
    if(NOT DEFINED CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_NO_WARNINGS)
      set(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_NO_WARNINGS ON)
    endif()
    include(${CMAKE_ROOT}/Modules/InstallRequiredSystemLibraries.cmake)
  endif()

  set(UVGAMI_PACKAGEDESCRIPTION_SUMMARY "UVgami")
  set(UVGAMI_PACKAGECONTACT "dani3lb0x3r@gmail.com")

  set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "UVgami : automated UV unwrapper for Blender")
  set(CPACK_PACKAGE_VENDOR           "")
  set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.txt")
  set(CPACK_RESOURCE_FILE_LICENSE    "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.txt")
  set(CPACK_PACKAGE_VERSION_MAJOR    "${UVGAMI_VERSION_MAJOR}")
  set(CPACK_PACKAGE_VERSION_MINOR    "${UVGAMI_VERSION_MINOR}")
  set(CPACK_PACKAGE_VERSION_PATCH    "${UVGAMI_VERSION_BUILD}")
  set(CPACK_PACKAGE_INSTALL_DIRECTORY "UVgami ${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}")
  set(CPACK_SOURCE_PACKAGE_FILE_NAME  "UVgami-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")

  # Make this explicit here, rather than accepting the CPack default value,
  # so we can refer to it:
  set(CPACK_PACKAGE_NAME "UVgami")

  if(NOT DEFINED CPACK_SYSTEM_NAME)
    set(CPACK_SYSTEM_NAME ${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR})
  endif()
  if(${CPACK_SYSTEM_NAME} MATCHES Windows)
    if(CMAKE_CL_64)
      set(CPACK_SYSTEM_NAME win64-x64)
    else()
      set(CPACK_SYSTEM_NAME win32-x86)
    endif()
  endif()

  if(NOT DEFINED CPACK_PACKAGE_FILE_NAME)
      set(CPACK_PACKAGE_FILE_NAME "${CPACK_SOURCE_PACKAGE_FILE_NAME}-${CPACK_SYSTEM_NAME}")
  endif()

  set(CPACK_BUNDLE_NAME "UVgami ${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}")

  set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)
  set(CPACK_COMPONENTS_ALL_IN_ONE_PACKAGE ON)
  install(FILES
    ${CPACK_RESOURCE_FILE_LICENSE}
    DESTINATION .
    COMPONENT Metadata
    EXCLUDE_FROM_ALL
  )
  include(CPack)
endiF(EXISTS "${CMAKE_ROOT}/Modules/CPack.cmake")
