name: Release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: "Which part of the version to increment"
        type: choice
        options:
          - major
          - minor
          - patch
        default: "patch"
        required: true

      use_old_engine:
        description: "Upload previous engine"
        type: boolean
        default: "true"
        required: true

      version:
        description: "Override version increment"
        required: false

env:
  ADDON_NAME: "UVgami"
  INCLUDED_FILES: "src LICENSE __init__.py"
  ENGINE_PREFIX: uvgami-engine

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # this needs to be before engine download
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get Next Version
        id: get_version
        uses: danielboxer/next-version-action@v1
        with:
          increment: ${{ github.event.inputs.increment }}
          version: ${{ github.event.inputs.version }}
          use_v_prefix: true

      # 1. get engine zips from previous release
      - name: Download engines
        id: download_engines
        if: ${{ github.event.inputs.use_old_engine == 'true' }}
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: "${{ env.ENGINE_PREFIX }}-*.zip"
        continue-on-error: true

      # 2. package add-on
      - name: Move to nested folder
        run: |
          mkdir $ADDON_NAME
          mv $INCLUDED_FILES $ADDON_NAME

      - name: Zip folder
        run: zip -r ${ADDON_NAME}.zip $ADDON_NAME

      # 3. create new release
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.new_version }}
          files: ${{ env.ADDON_NAME }}.zip

      # 4. upload engine if not new
      - name: Upload engine
        if: ${{ github.event.inputs.use_old_engine == 'true' && fromJSON(steps.download_engines.outputs.downloaded_files || '[]').length > 0 }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.new_version }}
          files: "${{ env.ENGINE_PREFIX }}-*.zip"
